<?php

namespace Joomla\Plugin\System\Altoimporter\Models;

use Illuminate\Database\Eloquent\Model;
use Joomla\CMS\Factory;

class OsProperty extends Model
{
    public $timestamps = false;

    protected $table;

    protected $fillable = [
        'id',
        'ref',
        'pro_name',
        'pro_alias',
        'pro_browser_title',
        'agent_id',
        'company_id',
        'category_id',
        'price',
        'price_original',
        'curr',
        'pro_small_desc',
        'pro_full_desc',
        'pro_type',
        'isFeatured',
        'isSold',
        'soldOn',
        'note',
        'lat_add',
        'long_add',
        'gbase_address',
        'price_call',
        'gbase_url',
        'pro_video',
        'address',
        'city',
        'state',
        'region',
        'country',
        'province',
        'postcode',
        'show_address',
        'hits',
        'metadesc',
        'metakey',
        'created',
        'created_by',
        'modified',
        'modified_by',
        'access',
        'publish_up',
        'publish_down',
        'remove_date',
        'published',
        'approved',
        'pro_pdf',
        'pro_pdf_file',
        'panorama',
        'bed_room',
        'bath_room',
        'rooms',
        'parking',
        'energy',
        'climate',
        'rent_time',
        'square_feet',
        'lot_size',
        'number_of_floors',
        'number_votes',
        'total_points',
        'total_request_info',
        'request_to_approval',
        'request_featured',
        'posted_by',
        'living_areas',
        'garage_description',
        'built_on',
        'remodeled_on',
        'house_style',
        'house_construction',
        'exterior_finish',
        'roof',
        'flooring',
        'floor_area_lower',
        'floor_area_main_level',
        'floor_area_upper',
        'floor_area_total',
        'basement_foundation',
        'basement_size',
        'percent_finished',
        'subdivision',
        'land_holding_type',
        'land_area',
        'total_acres',
        'lot_dimensions',
        'frontpage',
        'depth',
        'takings',
        'returns',
        'net_profit',
        'business_type',
        'stock',
        'fixtures',
        'fittings',
        'percent_office',
        'percent_warehouse',
        'loading_facilities',
        'fencing',
        'rainfall',
        'soil_type',
        'grazing',
        'cropping',
        'irrigation',
        'water_resources',
        'carrying_capacity',
        'storage',
        'price_text',
        'e_class',
        'c_class',
        'tour_link',
        'pro_pdf_file1',
        'pro_pdf_file2',
        'pro_pdf_file3',
        'pro_pdf_file4',
        'pro_pdf_file5',
        'pro_pdf_file6',
        'pro_pdf_file7',
        'pro_pdf_file8',
        'pro_pdf_file9',
        'ordering',
        'pro_name_cy',
        'pro_alias_cy',
        'address_cy',
        'price_text_cy',
        'pro_small_desc_cy',
        'pro_full_desc_cy',
        'metadesc_cy',
        'metakey_cy',
        'pro_browser_title_cy',
        'region_cy',
        'alto_id'
    ];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->table = Factory::getDbo()->getPrefix() . 'osrs_properties';
    }
}
